application: hacker-house
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: index.html
  upload: index.html

# Templates stuff:
- url: /assets
  static_dir: assets

- url: /DOCS
  static_dir: DOCS

- url: /images
  static_dir: images

- url: /PSD
  static_dir: PSD

- url: /ScreenShot
  static_dir: ScreenShot

# Booking Stuff:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: /favicon.ico

libraries:
- name: webapp2
  version: "2.5.2"
